prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  server:
    persistentVolume:
      enabled: true
      existingClaim: "prometheus-nfs-pvc"
      volumeName: "prometheus-nfs-pv"