apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-usb-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  nfs:
    path: /volume2/prom
    server: apespace.local
